name: SIIGO DEBUG VERSION1 CHECK
on:
  workflow_dispatch:

jobs:
  run-siigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script SIIGO
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SIIGO_USERNAME: ${{ secrets.SIIGO_USERNAME }}
          SIIGO_PASSWORD: ${{ secrets.SIIGO_PASSWORD }}
          SIIGO_ACCESS_KEY: ${{ secrets.SIIGO_ACCESS_KEY }}
        run: python siigo_sync.py
