name: Ejecutar SIIGO

on:
  workflow_dispatch:

jobs:
  run-siigo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ver archivos
        run: ls -la

      - name: Mostrar script
        run: cat siigo_sync.py
